name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    if: github.repository_owner == 'RealShadowNova'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: ${{ github.event.inputs.ref || '' }}
      - name: Use Node.js v16
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Documentation
        run: yarn docs
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: docs
          path: docs/api.json
      - name: Set Output
        id: env
        run: |
          echo "::set-output name=NAME::${GITHUB_REF_NAME}"
          echo "::set-output name=TYPE::${GITHUB_REF_TYPE}"
          echo "::set-output name=SHA::${GITHUB_SHA}"

  upload:
    name: Upload Documentation
    needs: build
    runs-on: ubuntu-latest
    env:
      NAME: ${{ github.event.inputs.ref || needs.build.outputs.NAME }}
      TYPE: ${{ needs.build.outputs.TYPE }}
      SHA: ${{ needs.build.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js v16
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Download Documentation Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: docs
          path: docs
      - name: Checkout Documentation Project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: 'RealShadowNova/docs'
          token: ${{ secrets.NOVA_TOKEN }}
          path: 'out'

      - name: Move Documentation
        if: ${{ (github.event.inputs.ref || env.TYPE) == 'tag' }}
        env:
          SEMVER: ${{ env.NAME }}
        run: |
          mkdir -p out/docs/typedoc-json-parser
          mv docs/api.json out/docs/typedoc-json-parser/${SEMVER}.json
      - name: Move Documentation
        if: ${{ !github.event.inputs.ref && env.TYPE == 'branch' }}
        run: |
          mkdir -p out/docs/typedoc-json-parser
          mv docs/api.json out/docs/typedoc-json-parser/${NAME}.json

      - name: Commit & Push
        run: |
          cd out

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add .
          git commit -m "docs(typedoc-json-parser): build for ${TYPE} ${NAME}: ${SHA}" || true
          git pull
          git push
